# Generated by Django 3.2.5 on 2021-08-07 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knitrous', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='clan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=122)),
                ('last', models.CharField(max_length=122)),
                ('email', models.CharField(max_length=122)),
                ('phone', models.CharField(max_length=13)),
                ('desc', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
    ]
